#!/usr/bin/perl
#
# creates a child process per chain
#usage perl forkFilter.pl #forks
use warnings;
use strict;
use Parallel::ForkManager;

my $max = shift(@ARGV); #get number of cores to use at one time
my $pm = Parallel::ForkManager->new($max);

my @climvars = (1,2,3);
foreach my $ch (1..4){
#       CHAINS:
        foreach my $cv (@climvars){
                $pm->start and next; #CHAINS; ##fork;
                print "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 6 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/bart_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/bart"."$cv.txt -outprefix bart"."$cv"."_"."$ch\n";
                #print "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 3 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/cali_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/cali"."$cv.txt -outprefix cali"."$cv"."_"."$ch\n";
                print "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 12 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/chum_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/chum"."$cv.txt -outprefix chum"."$cv"."_"."$ch\n";
                #print "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 6 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/cris_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/cris"."$cv.txt -outprefix cris"."$cv"."_"."$ch\n";
                #print "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 5 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/knul_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/knul"."$cv.txt -outprefix knul"."$cv"."_"."$ch\n";
                #print "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 4 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/land_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/land"."$cv.txt -outprefix land"."$cv"."_"."$ch\n";
                print "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 11 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/podu_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/podu"."$cv.txt -outprefix podu"."$cv"."_"."$ch\n";
                #print "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 5 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/popp_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/popp"."$cv.txt -outprefix popp"."$cv"."_"."$ch\n";
                system"sleep 2\n";
                system "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 6 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/bart_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/bart"."$cv.txt -outprefix bart"."$cv"."_"."$ch\n";
                #system "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 3 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/cali_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/cali"."$cv.txt -outprefix cali"."$cv"."_"."$ch\n";
                system "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 12 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/chum_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/chum"."$cv.txt -outprefix chum"."$cv"."_"."$ch\n";
                #system "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 6 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/cris_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/cris"."$cv.txt -outprefix cris"."$cv"."_"."$ch\n";
                #system "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 5 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/knul_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/knul"."$cv.txt -outprefix knul"."$cv"."_"."$ch\n";
                #system "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 4 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/land_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/land"."$cv.txt -outprefix land"."$cv"."_"."$ch\n";
                system "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 11 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/podu_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/podu"."$cv.txt -outprefix podu"."$cv"."_"."$ch\n";
                #system "/uufs/chpc.utah.edu/common/home/u6007910/projects/lmelissa_hostAdaptation/bayPass/baypass_2.1/sources/g_baypass -npilot 10 -nthreads 24 -npop 5 -nval 500 -thin 100 -burnin 20000 -gfile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/genofiles/popp_genofile.txt  -efile /uufs/chpc.utah.edu/common/home/u6007910/projects/timema_adaptation/analyses/baypass/pcvars_run/environfiles/popp"."$cv.txt -outprefix popp"."$cv"."_"."$ch\n";
                        $pm->finish; ## exit the child process
                }
        }

$pm->wait_all_children;
